name: "✨ Feature Request"
description: "Suggest a new feature or improvement"
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "### 💡 Feature Description"
  - type: textarea
    attributes:
      label: "Describe the Feature"
      description: "What feature would you like to see?"
  - type: textarea
    attributes:
      label: "Use Case"
      description: "Explain why this feature is useful."
  - type: textarea
    attributes:
      label: "Alternatives"
      description: "Any alternative solutions?"
  - type: input
    attributes:
      label: "Additional Context"
